#!/usr/bin/env bun

// read lines from colors.txt
// parse each line into a color name and hex value
// create a css variable for each color
// NOTE: only use Bun file APIs here

const colors = await Bun.file(import.meta.dir + "/colors.txt").text()

const variables = []
for (const line of colors.split("\n")) {
  if (!line.trim()) continue
  const [variable] = line.trim().split(":")
  const name = variable!.trim().substring(2)
  variables.push(`--color-${name}: var(--${name});`)
}

const output = `
/* Generated by script/colors.ts */
/* Do not edit this file manually */

@theme {
  --color-*: initial;
  ${variables.join("\n  ")}
}
`

// write to src/tailwind-colors.css
Bun.file(import.meta.dir + "/../src/tailwind-colors.css").write(output.trim())

// Bun.file(import.meta.dir + "../src/tailwind-colors.css").write(output.trim())
