"""A client library for accessing opencode

This package is generated by openapi-python-client.
A thin convenience wrapper `OpenCodeClient` is also provided.
"""

from .client import AuthenticatedClient, Client
from .extras import OpenCodeClient

__all__ = (
    "AuthenticatedClient",
    "Client",
    "OpenCodeClient",
)
